# Generated by Django 4.2.5 on 2023-11-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('microchip', models.CharField(max_length=50)),
                ('tratamiento', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=150)),
                ('valor_de_tratamiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_de_atencion', models.DateField(max_length=50)),
                ('motivo_de_atencion', models.CharField(max_length=50)),
                ('diagnostico', models.CharField(max_length=100)),
                ('valor_consulta', models.CharField(max_length=50)),
                ('microchip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoVetIssidora.tratamientos')),
            ],
        ),
    ]
